const categories = {
  Dogs:["Food","Toys","Grooming","Beds"],Cats:["Litter","Food","Trees","Toys"],Birds:["Cages","Feed","Perches"],Fish:["Aquariums","Filters","Lighting"],"Small Animals":["Habitats","Bedding","Chews"],Reptiles:["Terrariums","Heating","Supplements"]
};
const products = [
  {id:1,name:"Canine Crunch Pro",brand:"PetHarvest",category:"Dogs",rating:4.7,price:34,image:"https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=600&q=80",description:"High-protein dry dog food for active breeds.",pros:["Protein-rich","Digestive support"],cons:["Not grain-free"],links:["Chewy","Amazon"],reviews:["My lab loves it!","Improved coat shine."]},
  {id:2,name:"PurrCloud Litter",brand:"WhiskerHome",category:"Cats",rating:4.5,price:19,image:"https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=600&q=80",description:"Low-dust clumping litter with odor lock.",pros:["Great odor control"],cons:["Heavy bag"],links:["Petco","Walmart"],reviews:["Works all week."]},
  {id:3,name:"FeatherFit Flight Cage",brand:"AviaryCo",category:"Birds",rating:4.8,price:129,image:"https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=600&q=80",description:"Spacious cage with easy-clean tray.",pros:["Large interior"],cons:["Assembly time"],links:["Amazon"],reviews:["Perfect for parakeets."]},
  {id:4,name:"AquaClear 50 Filter",brand:"BlueTank",category:"Fish",rating:4.6,price:42,image:"https://images.unsplash.com/photo-1513863323964-766de767f20e?auto=format&fit=crop&w=600&q=80",description:"Quiet power filter for 20-50 gal aquariums.",pros:["Silent","Reliable"],cons:["Cartridge costs"],links:["Chewy"],reviews:["Crystal clear water."]},
  {id:5,name:"HammyHide Habitat",brand:"TinyPaws",category:"Small Animals",rating:4.4,price:58,image:"https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=600&q=80",description:"Modular habitat for hamsters and gerbils.",pros:["Expandable"],cons:["Plastic clips"],links:["PetSmart"],reviews:["Hamster explores nonstop."]},
  {id:6,name:"SunBask Heat Lamp",brand:"ReptiGlow",category:"Reptiles",rating:4.5,price:27,image:"https://images.unsplash.com/photo-1534707254970-00153427a3f5?auto=format&fit=crop&w=600&q=80",description:"UVB/UVA heat lamp for reptile terrariums.",pros:["Good spectrum"],cons:["Bulb lifespan"],links:["Amazon","Chewy"],reviews:["Bearded dragon active."]}
];
for(let i=7;i<=20;i++){const c=Object.keys(categories)[(i-1)%6];products.push({id:i,name:`${c} Essential ${i}`,brand:["PetNest","CozyCritter","VitaPaw"][i%3],category:c,rating:parseFloat((3.8+(i%12)/10).toFixed(1)),price:10+i*4,image:`https://picsum.photos/seed/pet${i}/600/400`,description:`Reliable ${c.toLowerCase()} product designed for comfort and wellness.`,pros:["Durable","Value for money"],cons:["Limited color options"],links:["Amazon","Petco"],reviews:["Great quality.","Would buy again."]});}
