const page=document.body.dataset.page;const qs=new URLSearchParams(location.search);const byId=id=>document.getElementById(id);
const catStyle={Dogs:['🐕','linear-gradient(135deg,#2d6a4f,#95d5b2)'],Cats:['🐱','linear-gradient(135deg,#4c1d95,#60a5fa)'],Birds:['🦜','linear-gradient(135deg,#0ea5e9,#bfdbfe)'],Fish:['🐠','linear-gradient(135deg,#0f766e,#5eead4)'],'Small Animals':['🐹','linear-gradient(135deg,#f59e0b,#fdba74)'],Reptiles:['🦎','linear-gradient(135deg,#65a30d,#fde047)']};
const stars=r=>{const full=Math.floor(r);return '★'.repeat(full)+'☆'.repeat(5-full)};
const productCard=(p,i=0)=>`<article class="product-card" style="animation-delay:${i*70}ms"><button class="favorite" aria-label="Favorite">♡</button><div class="product-image" style="background:${catStyle[p.category][1]}"></div><div class="product-body"><div class="brand">${p.brand}</div><h3>${p.name}</h3><div class="rating">${stars(p.rating)}</div><p class="meta">${p.category}</p><p class="price">$${p.price}</p><a class="btn" href="product-detail.html?id=${p.id}">View Details</a></div></article>`;
function setupNav(){const b=document.querySelector('.menu-toggle'),n=document.querySelector('.main-nav');b?.addEventListener('click',()=>n.classList.toggle('open'));}
function setupSearch(){const input=byId('global-search'),list=byId('autocomplete-list');if(!input||!list)return;input.addEventListener('input',()=>{const q=input.value.toLowerCase().trim();if(!q){list.style.display='none';return;}const m=products.filter(p=>p.name.toLowerCase().includes(q)||p.brand.toLowerCase().includes(q)).slice(0,6);list.innerHTML=m.map(p=>`<li data-id="${p.id}">${p.name} <span class='meta'>${p.brand}</span></li>`).join('');list.style.display=m.length?'block':'none';});list.addEventListener('click',e=>{const li=e.target.closest('li');if(li)location.href=`product-detail.html?id=${li.dataset.id}`;});}
function renderHome(){byId('category-grid').innerHTML=Object.keys(categories).map((c,i)=>`<a class="category-card" style="animation-delay:${i*90}ms" href="category.html?category=${encodeURIComponent(c)}"><div class="category-top" style="background:${catStyle[c][1]}">${catStyle[c][0]}</div><div class="category-body"><h3>${c}</h3><p class="meta">${products.filter(p=>p.category===c).length} products</p><span class="link-btn">Browse →</span></div></a>`).join('');byId('trending-products').innerHTML=[...products].sort((a,b)=>b.rating-a.rating).slice(0,6).map((p,i)=>productCard(p,i)).join('');}
function renderProducts(){let data=[...products];const q=qs.get('q');if(q)data=data.filter(p=>`${p.name} ${p.brand}`.toLowerCase().includes(q.toLowerCase()));const cg=byId('filter-category');Object.keys(categories).forEach(c=>cg.innerHTML+=`<option>${c}</option>`);const paint=()=>{let r=[...data],c=cg.value,pr=byId('filter-price').value,rt=byId('filter-rating').value,s=byId('sort-products').value;if(c)r=r.filter(p=>p.category===c);if(pr==='low')r=r.filter(p=>p.price<20);if(pr==='mid')r=r.filter(p=>p.price>=20&&p.price<=60);if(pr==='high')r=r.filter(p=>p.price>60);if(rt)r=r.filter(p=>p.rating>=parseFloat(rt));if(s==='name')r.sort((a,b)=>a.name.localeCompare(b.name));if(s==='rating')r.sort((a,b)=>b.rating-a.rating);if(s==='price')r.sort((a,b)=>a.price-b.price);byId('products-grid').innerHTML=r.map((p,i)=>productCard(p,i)).join('');};['filter-category','filter-price','filter-rating','sort-products'].forEach(id=>byId(id).addEventListener('change',paint));paint();}
function renderDetail(){const p=products.find(x=>x.id===parseInt(qs.get('id')));if(!p)return byId('product-detail').innerHTML='<p>Product not found.</p>';const rev=p.reviews.map((r,i)=>`<div class='review-card'><p><span class='avatar'>U${i+1}</span><strong>User ${i+1}</strong> <span class='meta'>• May ${i+2}, 2026</span></p><div class='rating'>${stars(p.rating)}</div><p>${r}</p></div>`).join('');byId('product-detail').innerHTML=`<nav class='breadcrumb'>Home / Products / ${p.category} / ${p.name}</nav><div class='detail-layout'><div class='detail-image' style='background:${catStyle[p.category][1]}'>${catStyle[p.category][0]}</div><div><h1>${p.name}</h1><p class='brand'>${p.brand}</p><div class='rating'>${stars(p.rating)} <span class='meta'>(${p.rating})</span></div><p class='price'>$${p.price}</p><p>${p.description}</p><h3>Where to Buy</h3><p class='buy-links'><a class='amazon' href='#'>Amazon</a><a class='chewy' href='#'>Chewy</a><a class='petsmart' href='#'>PetSmart</a></p><div class='pros-cons'><div class='pros'><h3>✓ Pros</h3><ul>${p.pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class='cons'><h3>✗ Cons</h3><ul>${p.cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><h3>User Reviews</h3>${rev}</div></div>`;}
function renderCategory(){const c=qs.get('category')||'Dogs';byId('category-title').textContent=`${c} Products`;byId('category-description').textContent=`Discover top-rated ${c.toLowerCase()} essentials from trusted brands.`;byId('subcategory-tags').innerHTML=(categories[c]||[]).map(s=>`<a class='tag' href='#'>${s}</a>`).join('');byId('category-products').innerHTML=products.filter(p=>p.category===c).map((p,i)=>productCard(p,i)).join('');}
setupNav();setupSearch();if(page==='home')renderHome();if(page==='products')renderProducts();if(page==='detail')renderDetail();if(page==='category')renderCategory();
