const page=document.body.dataset.page;const qs=new URLSearchParams(location.search);const byId=id=>document.getElementById(id);
const productCard=p=>`<article class="product-card"><div class="product-img placeholder">🐾</div><div class="product-body"><div class="product-brand">${p.brand}</div><div class="product-name">${p.name}</div><div class="rating">${p.rating} ★</div><div class="product-meta"><span class="product-category">${p.category}</span></div></div><div class="product-footer"><span class="product-price">$${p.price}</span><a class="btn-view" href="product-detail.html?id=${p.id}">View Details</a></div></article>`;
function setupNav(){const b=document.querySelector('.menu-toggle'),n=document.querySelector('.main-nav');b?.addEventListener('click',()=>n.classList.toggle('open'));}
function setupSearch(){const input=byId('global-search'),list=byId('autocomplete-list');if(!input||!list)return;input.addEventListener('input',()=>{const q=input.value.toLowerCase().trim();if(!q){list.style.display='none';return;}const m=products.filter(p=>p.name.toLowerCase().includes(q)||p.brand.toLowerCase().includes(q)).slice(0,6);list.innerHTML=m.map(p=>`<li data-id="${p.id}">${p.name} <span class='meta'>${p.brand}</span></li>`).join('');list.style.display=m.length?'block':'none';});list.addEventListener('click',e=>{const li=e.target.closest('li');if(li)location.href=`product-detail.html?id=${li.dataset.id}`;});}
function renderHome(){byId('category-grid').innerHTML=Object.keys(categories).map(c=>`<a class="category-card" href="category.html?category=${encodeURIComponent(c)}"><span class="cat-icon">🐶</span><h3>${c}</h3><p class="meta">${products.filter(p=>p.category===c).length} products</p><div class="cat-arrow">Browse →</div></a>`).join('');byId('trending-products').innerHTML=[...products].sort((a,b)=>b.rating-a.rating).slice(0,6).map(p=>productCard(p)).join('');}
function renderProducts(){let data=[...products];const q=qs.get('q');if(q)data=data.filter(p=>`${p.name} ${p.brand}`.toLowerCase().includes(q.toLowerCase()));const cg=byId('filter-category');Object.keys(categories).forEach(c=>cg.innerHTML+=`<option>${c}</option>`);const paint=()=>{let r=[...data],c=cg.value,pr=byId('filter-price').value,rt=byId('filter-rating').value,s=byId('sort-products').value;if(c)r=r.filter(p=>p.category===c);if(pr==='low')r=r.filter(p=>p.price<20);if(pr==='mid')r=r.filter(p=>p.price>=20&&p.price<=60);if(pr==='high')r=r.filter(p=>p.price>60);if(rt)r=r.filter(p=>p.rating>=parseFloat(rt));if(s==='name')r.sort((a,b)=>a.name.localeCompare(b.name));if(s==='rating')r.sort((a,b)=>b.rating-a.rating);if(s==='price')r.sort((a,b)=>a.price-b.price);byId('products-grid').innerHTML=r.map(p=>productCard(p)).join('');};['filter-category','filter-price','filter-rating','sort-products'].forEach(id=>byId(id).addEventListener('change',paint));paint();}
function renderDetail(){const p=products.find(x=>x.id===parseInt(qs.get('id')));if(!p)return byId('product-detail').innerHTML='<p>Product not found.</p>';const rev=p.reviews.map((r,i)=>`<div class='review-card'><div class='review-header'><span class='avatar'>U${i+1}</span><p><strong>User ${i+1}</strong> <span class='meta'>• May ${i+2}, 2026</span></p></div><div class='rating'>${p.rating} ★</div><p>${r}</p></div>`).join('');byId('product-detail').innerHTML=`<nav class='breadcrumb'>Home / Products / ${p.category} / ${p.name}</nav><div class='detail-layout'><div class='detail-image'>🐾</div><div class='detail-info'><h1>${p.name}</h1><p class='product-brand'>${p.brand}</p><div class='rating'>${p.rating} ★</div><p class='price'>$${p.price}</p><p>${p.description}</p><h3>Where to Buy</h3><div class='buy-links'><a class='amazon' href='#'>Amazon</a><a class='chewy' href='#'>Chewy</a><a class='petsmart' href='#'>PetSmart</a></div><div class='pros-cons'><div class='pros'><h3>Pros</h3><ul>${p.pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class='cons'><h3>Cons</h3><ul>${p.cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><h3>User Reviews</h3>${rev}</div></div>`;}
function renderCategory(){const c=qs.get('category')||'Dogs';byId('category-title').textContent=`${c} Products`;byId('category-description').textContent=`Discover top-rated ${c.toLowerCase()} essentials from trusted brands.`;byId('subcategory-tags').innerHTML=(categories[c]||[]).map(s=>`<a class='tag' href='#'>${s}</a>`).join('');byId('category-products').innerHTML=products.filter(p=>p.category===c).map(p=>productCard(p)).join('');}
setupNav();setupSearch();if(page==='home')renderHome();if(page==='products')renderProducts();if(page==='detail')renderDetail();if(page==='category')renderCategory();
