const page=document.body.dataset.page;const qs=new URLSearchParams(location.search);
const byId=id=>document.getElementById(id);
const card=p=>`<article class="card"><img src="${p.image}" alt="${p.name}"><h3>${p.name}</h3><p class="meta">${p.brand} • ${p.category} • ⭐ ${p.rating}</p><p>${p.description}</p><p class="price">$${p.price}</p><a href="product-detail.html?id=${p.id}">View details</a></article>`;
function setupNav(){const b=document.querySelector('.menu-toggle'),n=document.querySelector('.main-nav');b?.addEventListener('click',()=>n.classList.toggle('open'));}
function setupSearch(){const input=byId('global-search'),list=byId('autocomplete-list');if(!input||!list)return;input.addEventListener('input',()=>{const q=input.value.toLowerCase().trim();if(!q){list.style.display='none';return;}const m=products.filter(p=>p.name.toLowerCase().includes(q)||p.brand.toLowerCase().includes(q)).slice(0,6);list.innerHTML=m.map(p=>`<li data-id="${p.id}">${p.name} <span class='meta'>${p.brand}</span></li>`).join('');list.style.display=m.length?'block':'none';});list.addEventListener('click',e=>{const li=e.target.closest('li');if(!li)return;location.href=`product-detail.html?id=${li.dataset.id}`;});}
function renderHome(){byId('category-grid').innerHTML=Object.keys(categories).map(c=>`<a class="card" href="category.html?category=${encodeURIComponent(c)}"><h3>${c}</h3><p>${categories[c].join(' • ')}</p></a>`).join('');byId('trending-products').innerHTML=[...products].sort((a,b)=>b.rating-a.rating).slice(0,6).map(card).join('');}
function renderProducts(){let data=[...products];const q=qs.get('q');if(q)data=data.filter(p=>`${p.name} ${p.brand}`.toLowerCase().includes(q.toLowerCase()));const cg=byId('filter-category');Object.keys(categories).forEach(c=>cg.innerHTML+=`<option>${c}</option>`);const paint=()=>{let r=[...data],c=cg.value,pr=byId('filter-price').value,rt=byId('filter-rating').value,s=byId('sort-products').value;if(c)r=r.filter(p=>p.category===c);if(pr==='low')r=r.filter(p=>p.price<20);if(pr==='mid')r=r.filter(p=>p.price>=20&&p.price<=60);if(pr==='high')r=r.filter(p=>p.price>60);if(rt)r=r.filter(p=>p.rating>=parseFloat(rt));if(s==='name')r.sort((a,b)=>a.name.localeCompare(b.name));if(s==='rating')r.sort((a,b)=>b.rating-a.rating);if(s==='price')r.sort((a,b)=>a.price-b.price);byId('products-grid').innerHTML=r.map(card).join('');};['filter-category','filter-price','filter-rating','sort-products'].forEach(id=>byId(id).addEventListener('change',paint));paint();}
function renderDetail(){const p=products.find(x=>x.id===parseInt(qs.get('id')));if(!p)return byId('product-detail').innerHTML='<p>Product not found.</p>';byId('product-detail').innerHTML=`<div class='detail-layout'><div class='gallery'><img src='${p.image}' alt='${p.name}'><img src='https://picsum.photos/seed/detail${p.id}/700/450' alt='${p.name} alt'></div><div><h1>${p.name}</h1><p class='meta'>${p.brand} • ${p.category} • ⭐ ${p.rating}</p><p class='price'>$${p.price}</p><p>${p.description}</p><h3>Pros</h3><ul>${p.pros.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Cons</h3><ul>${p.cons.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Where to buy</h3><p class='buy-links'>${p.links.map(l=>`<a href='#'>${l}</a>`).join('')}</p><h3>User reviews</h3><ul>${p.reviews.map(r=>`<li>${r}</li>`).join('')}</ul></div></div>`;}
function renderCategory(){const c=qs.get('category')||'Dogs';byId('category-title').textContent=`${c} Products`;byId('category-description').textContent=`Discover top-rated ${c.toLowerCase()} essentials from trusted brands.`;byId('subcategory-tags').innerHTML=(categories[c]||[]).map(s=>`<span class='tag'>${s}</span>`).join('');byId('category-products').innerHTML=products.filter(p=>p.category===c).map(card).join('');}
setupNav();setupSearch();if(page==='home')renderHome();if(page==='products')renderProducts();if(page==='detail')renderDetail();if(page==='category')renderCategory();
